# default.yml controls global settings and policies/queries that run on all hosts ("All teams").

policies:
queries:
  - path: lib/all/both/queries/
  - path: lib/linux/both/queries/
  - path: lib/macos/both/queries/
  - path: lib/windows/both/queries/
agent_options:
controls:
org_settings:
  server_settings:
    server_url: $FLEET_URL
  org_info:
    org_name: Fleet
  secrets:
    - secret: "$FLEET_GLOBAL_ENROLL_SECRET"
